version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
platform:
- AnyCPU
#environment:
  # Don't report back to the mothership
  #DOTNET_CLI_TELEMETRY_OPTOUT: 1
build:
  verbosity: minimal
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
#- ps: appveyor DownloadFile https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe -FileName "c:\dotnet.exe"
#- cmd: call c:\dotnet.exe /quiet
before_build:
- appveyor-retry dotnet restore "DaisyChain\\Lavspent.DaisyChain\\Lavspent.DaisyChain.csproj" -v Minimal -r "%PLATFORM%"
- appveyor-retry dotnet restore "DaisyChain\\Lavspent.DaisyChain.Devices\\Lavspent.DaisyChain.Devices.csproj" -v Minimal -r "%PLATFORM%"
- appveyor-retry dotnet restore "DaisyChain\\Lavspent.DaisyChain.Firmata\\Lavspent.DaisyChain.Firmata.csproj" -v Minimal -r "%PLATFORM%"
- appveyor-retry dotnet restore "DaisyChain\\Lavspent.DaisyChain.Fluent\\Lavspent.DaisyChain.Fluent.csproj" -v Minimal -r "%PLATFORM%"
- appveyor-retry dotnet restore "DaisyChain\\Lavspent.DaisyChain.Mocks\\Lavspent.DaisyChain.Mocks.csproj" -v Minimal -r "%PLATFORM%"
- appveyor-retry nuget restore "DaisyChain\\Lavspent.DaisyChain.Net45\\Lavspent.DaisyChain.Net45.csproj"
#- appveyor-retry nuget restore "DaisyChain\\Lavspent.DaisyChain.Uwp\\Lavspent.DaisyChain.Uwp.csproj"  

#- appveyor-retry dotnet restore #src\ks -v Minimal -r %PLATFORM%
build_script:
- dotnet build "DaisyChain\\Lavspent.DaisyChain\\Lavspent.DaisyChain.csproj" -c %CONFIGURATION% -r "%PLATFORM%"  --version-suffix %LABEL%
- dotnet build "DaisyChain\\Lavspent.DaisyChain.Devices\\Lavspent.DaisyChain.Devices.csproj" -c %CONFIGURATION% -r "%PLATFORM%"  --version-suffix %LABEL%
- dotnet build "DaisyChain\\Lavspent.DaisyChain.Firmata\\Lavspent.DaisyChain.Firmata.csproj" -c %CONFIGURATION% -r "%PLATFORM%"  --version-suffix %LABEL%
- dotnet build "DaisyChain\\Lavspent.DaisyChain.Fluent\\Lavspent.DaisyChain.Fluent.csproj" -c %CONFIGURATION% -r "%PLATFORM%"  --version-suffix %LABEL%
- dotnet build "DaisyChain\\Lavspent.DaisyChain.Mocks\\Lavspent.DaisyChain.Mocks.csproj" -c %CONFIGURATION% -r "%PLATFORM%"  --version-suffix %LABEL%
- msbuild "DaisyChain\\Lavspent.DaisyChain.Net45\\Lavspent.DaisyChain.Net45.csproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:OutDir="bin\%CONFIGURATION%"  /p:Configuration=%CONFIGURATION% /p:Platform="%PLATFORM%"
#msbuild "DaisyChain\\Lavspent.DaisyChain.Uwp\\Lavspent.DaisyChain.Uwp.csproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#- dotnet build "src\ks.model" -c %CONFIGURATION% -r %PLATFORM%  --no-dependencies --version-suffix %LABEL%

#after_build:
#- dotnet publish "src\ks" -c %CONFIGURATION% -r %PLATFORM% --version-suffix %LABEL% -o %APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%
#- 7z a zip\ks_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%\*.*

#artifacts:
#- path: zip\ks_$(platform).zip
#  name: arti_$(platform)
#deploy:
#  release: kscratch-v$(appveyor_build_version)
#  description: 'Commit build'
#  provider: GitHub
#  auth_token: 
#    secure: R1Od4gYaFkuhqpFUVBJpVZY4CRAeHuzgH4VQBMfWWXwEAEY4iVJo8sNBq4N+4enq # your encrypted token from GitHub
#  artifact: zip\ks_$(platform).zip            # upload all NuGet packages to release assets
#  draft: true
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: false        # deploy on tag push only 
#cache:
#- '%USERPROFILE%\.nuget\packages'
#on_finish: # Run the demo to show that it works